version: '3.9'
services:
  minecraft:
    image: ghcr.io/synchthia/mcserver/plain:latest
    container_name: "minecraft"
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    environment:
      TZ: "Asia/Tokyo"
      PORT: 25565
      # !!!
      # IF YOU WANT MOUNT VOLUMES,
      # UID/GID MUST BE Provide!!! (for directory / files permission)
      # !!!
      UID: "${USER_ID:-0}"
      GID: "${GROUP_ID:-0}"
    volumes:
      - type: bind
        source: ./local/server
        target: /app/server
      - type: bind
        source: ./local/config
        target: /app/config
      - type: bind
        source: ./local/worlds
        target: /app/worlds
      - type: bind
        source: ./local/plugins
        target: /app/plugins
